core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('', include('dashboard.urls')),
    path("auth/", include("django.contrib.auth.urls")),
]

dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('solicitacoes/',views.solicitacoes, name='solicitacoes'),
    path('entregadores/',views.entregadores, name='entregadores'),
    path('relatorios/',views.relatorios, name='relatorios'),
    path('config/', views.config, name='config'),
    path('change_password/', views.change_password, name='change_password'),
]

accounts/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

class API(models.Model):
    name = models.CharField(max_length=100)
    client_id = models.CharField(max_length=100)
    client_secret = models.CharField(max_length=100)
    certificado_producao = models.FileField(upload_to='efi/credentials/certificados/', blank=True, null=True)
    certificado_homologacao = models.FileField(upload_to='efi/credentials/certificados/', blank=True, null=True)
    sandbox = models.BooleanField(default=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from efipay import EfiPay # Importação SDK EFIPAY
from efi.credentials import credentials
from .models import API # Models para configuração dea API EFIPAY
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django import forms



efi = EfiPay(credentials.CREDENTIALS)


@login_required
def index(request):

    response = efi.get_account_balance()
    saldo = response.get('saldo')

    contexto = {
        'saldo': saldo
    }


    return render(request, 'dashboard/index.html', contexto)


@login_required
def solicitacoes(request):
    

    contexto = {
        
    }

    return render(request, 'dashboard/solicitacoes.html', contexto)


@login_required
def entregadores(request):
    contexto = {
        
    }

    return render(request, 'dashboard/entregadores.html', contexto)


@login_required
def relatorios(request):
    contexto = {
        
    }

    return render(request, 'dashboard/relatorios.html', contexto)



@login_required
def config(request):
    
    
    api = API.objects.get(pk=1)
    contexto = {
        'api': api
    }

    return render(request, 'dashboard/config.html', contexto)  # Substitua 'seu_template.html' pelo seu template HTML



class ChangePasswordForm(forms.Form): # Form personalizado para alterar senha
    old_password = forms.CharField(label='Senha Antiga', widget=forms.PasswordInput)
    new_password = forms.CharField(label='Nova Senha', widget=forms.PasswordInput)
    confirm_new_password = forms.CharField(label='Confirmar Nova Senha', widget=forms.PasswordInput)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data['old_password']
            new_password = form.cleaned_data['new_password']
            confirm_new_password = form.cleaned_data['confirm_new_password']
            
            if request.user.check_password(old_password) and new_password == confirm_new_password:
                request.user.set_password(new_password)
                request.user.save()
                messages.success(request, 'Sua senha foi alterada com sucesso!')
                return redirect('change_password')
            else:
                messages.error(request, 'Houve um erro ao alterar sua senha. Certifique-se de digitar corretamente a senha antiga e a nova senha.')
    else:
        form = ChangePasswordForm()
    
    return render(request, 'dashboard/change_password.html', {'form': form})

templates/dashboard/_base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="pt-br" class="dark">



<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Codeneiz: WalletPay</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>
{% if user.is_authenticated %}
{% include 'dashboard/navbar.html' %}
{% else %}
{% include 'registration/navbar.html' %}
{% endif %}

<body class="bg-green-50">


    <div class="container mx-auto mt-4 mb-28">
        {% block content %}
        {% endblock content %}
    </div>



    {% include 'dashboard/footer.html' %}









    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.0/flowbite.min.js"></script>
</body>

</html>

templates/dashboard/change_password.html
{% extends "dashboard/_base.html" %}

{% block content %}
<form class="max-w-sm mx-auto" method="post">
    {% csrf_token %}

    <div class="p-10 w-full bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-900 dark:border-gray-700">
        {% if messages %}
        {% for message in messages %}
        <div class="bg-blue-100 border-l-4 border-blue-500 text-blue-700 p-4 mb-4" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

        <div class="mb-6">
            <label for="id_old_password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Senha
                Antiga</label>
            <input type="password" id="id_old_password" name="old_password"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="•••••••••" required>
        </div>

        <div class="mb-6">
            <label for="id_new_password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nova
                Senha</label>
            <input type="password" id="id_new_password" name="new_password"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="•••••••••" required>
        </div>

        <div class="mb-6">
            <label for="id_confirm_new_password"
                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirmar Senha</label>
            <input type="password" id="id_confirm_new_password" name="confirm_new_password"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="•••••••••" required>
        </div>

        <button type="submit"
            class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Alterar
            Senha</button>
    </div>
</form>

{% endblock content %}

templates/dashboard/config copy.html
{% extends "dashboard/_base.html" %}

{% block content %}


<form method="post" enctype="multipart/form-data" class="max-w-sm mx-auto">
    <div class="mb-5">
        {% csrf_token %}
        <label for="name">Nome da API:</label><br>
        <input type="text" id="name" name="name" placeholder="{{ api.name }}"><br><br>

        <label for="client_id">Client ID:</label><br>
        <input type="text" id="client_id" name="client_id" placeholder="{{ api.client_id }}"><br><br>

        <label for="client_secret">Client Secret:</label><br>
        <input type="text" id="client_secret" name="client_secret" placeholder="{{ api.client_id }}"><br><br>

        <label for="sandbox">Sandbox:</label>
        <input type="checkbox" id="sandbox" name="sandbox" value="1"><br><br>

        <label for="certificado_producao">Certificado de Produção (PEM):</label><br>
        <input type="file" id="certificado_producao" name="certificado_producao" accept=".pem"><br><br>

        <label for="certificado_homologacao">Certificado de Homologação (PEM):</label><br>
        <input type="file" id="certificado_homologacao" name="certificado_homologacao" accept=".pem"><br><br>

        <input type="submit" value="Enviar">
    </div>
</form>



{% endblock content %}

templates/dashboard/config.html
{% extends "dashboard/_base.html" %}

{% block content %}





<div class="w-full bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-900 dark:border-gray-700">
    <ul class="flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-gray-200 rounded-t-lg bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:bg-gray-900"
        id="defaultTab" data-tabs-toggle="#defaultTabContent" role="tablist">
        <li class="me-2">
            <button id="status-tab" data-tabs-target="#status" type="button" role="tab" aria-controls="status"
                aria-selected="true"
                class="inline-block p-4 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300">Status</button>
        </li>

        <li class="me-2">
            <button id="producao-tab" data-tabs-target="#producao" type="button" role="tab" aria-controls="producao"
                aria-selected="false"
                class="inline-block p-4 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300">API
                Keys</button>
        </li>

        <li class="me-2">
            <button id="cert-tab" data-tabs-target="#cert" type="button" role="tab" aria-controls="cert"
                aria-selected="false"
                class="inline-block p-4 text-blue-600 rounded-ss-lg hover:bg-gray-100 dark:bg-gray-900 dark:hover:bg-gray-700 dark:text-blue-500">Certificados</button>
        </li>

    </ul>
    <div id="defaultTabContent">
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-900" id="cert" role="tabpanel"
            aria-labelledby="cert-tab">
            <h2 class="mb-3 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">Suporte do Sistema
                WalletPay</h2>
            <p class="mb-3 text-gray-500 dark:text-gray-400">

                Estamos aqui para ajudar! Se você tiver problemas técnicos, dúvidas sobre como usar as ferramentas ou
                quiser nos enviar sugestões, entre em contato. Nossa equipe está disponível para tornar sua experiência
                com o Sistema WalletPay melhor possível.

                <br><br> Como nos contatar:

                <br><br> Whatsapp: (67) 99104-4105
                <br>E-mail: amaury_mju@hotmail.com
                <br>Horário de Atendimento:
                <br>Segunda a sexta-feira, das 9h às 18h (horário local).

                <br><br>Agradecemos por escolher nossosserviços e estamos prontos para ajudar no que precisar!

                <br><br>Atenciosamente,
                Equipe de Suporte do Codeneiz
            </p>
            <a href="https://amaurygomes.com.br"
                class="inline-flex items-center font-medium text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-700">
                Nossa Página
                <svg class=" w-2.5 h-2.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                    fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m1 9 4-4-4-4" />
                </svg>
            </a>
        </div>
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-900" id="producao" role="tabpanel"
            aria-labelledby="producao-tab">
            <h2 class="mb-5 text-2xl font-extrabold tracking-tight text-gray-900 dark:text-white">Como usar o Sistema
            </h2>
            <!-- List -->
            <ul role="list" class="space-y-4 text-gray-500 dark:text-gray-400">
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Lorem ipsum dolor sit amet</span>
                </li>
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Nunc ipsum turpis</span>
                </li>
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Curabitur pharetra et diam in egestas</span>
                </li>
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Phasellus eu ligula metus</span>
                </li>
            </ul>
        </div>
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-900" id="status" role="tabpanel"
            aria-labelledby="status-tab">
            Status aqui
        </div>
    </div>
</div>




{% endblock content %}

templates/dashboard/footer.html
<footer
    class="fixed bottom-0 left-0 z-20 w-full p-4 bg-white border-t border-gray-200 shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-900 dark:border-gray-600">
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-300">© 2023 <a href="https://amaurygomes.com.br"
            class="hover:underline">Amaury Gomes</a>. All Rights Reserved.
    </span>

</footer>

templates/dashboard/index.html
{% extends "dashboard/_base.html" %}

{% block content %}





<div class="w-full bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-900 dark:border-gray-700">
    <ul class="flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-gray-200 rounded-t-lg bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:bg-gray-900"
        id="defaultTab" data-tabs-toggle="#defaultTabContent" role="tablist">
        <li class="me-2">
            <button id="statistics-tab" data-tabs-target="#statistics" type="button" role="tab"
                aria-controls="statistics" aria-selected="true"
                class="inline-block p-4 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300">Resumo</button>
        </li>

        <li class="me-2">
            <button id="services-tab" data-tabs-target="#services" type="button" role="tab" aria-controls="services"
                aria-selected="false"
                class="inline-block p-4 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300">Dicas</button>
        </li>

        <li class="me-2">
            <button id="support-tab" data-tabs-target="#support" type="button" role="tab" aria-controls="support"
                aria-selected="false"
                class="inline-block p-4 text-blue-600 rounded-ss-lg hover:bg-gray-100 dark:bg-gray-900 dark:hover:bg-gray-700 dark:text-blue-500">Suporte</button>
        </li>

    </ul>
    <div id="defaultTabContent">
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-900" id="support" role="tabpanel"
            aria-labelledby="support-tab">
            <h2 class="mb-3 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">Suporte do Sistema
                WalletPay</h2>
            <p class="mb-3 text-gray-500 dark:text-gray-400">

                Estamos aqui para ajudar! Se você tiver problemas técnicos, dúvidas sobre como usar as ferramentas ou
                quiser nos enviar sugestões, entre em contato. Nossa equipe está disponível para tornar sua experiência
                com o Sistema WalletPay melhor possível.

                <br><br> Como nos contatar:

                <br><br> Whatsapp: (67) 99104-4105
                <br>E-mail: amaury_mju@hotmail.com
                <br>Horário de Atendimento:
                <br>Segunda a sexta-feira, das 9h às 18h (horário local).

                <br><br>Agradecemos por escolher nossosserviços e estamos prontos para ajudar no que precisar!

                <br><br>Atenciosamente,
                Equipe de Suporte do Codeneiz
            </p>
            <a href="https://amaurygomes.com.br"
                class="inline-flex items-center font-medium text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-700">
                Nossa Página
                <svg class=" w-2.5 h-2.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                    fill="none" viewBox="0 0 6 10">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="m1 9 4-4-4-4" />
                </svg>
            </a>
        </div>
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-900" id="services" role="tabpanel"
            aria-labelledby="services-tab">
            <h2 class="mb-5 text-2xl font-extrabold tracking-tight text-gray-900 dark:text-white">Como usar o Sistema
            </h2>
            <!-- List -->
            <ul role="list" class="space-y-4 text-gray-500 dark:text-gray-400">
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Lorem ipsum dolor sit amet</span>
                </li>
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Nunc ipsum turpis</span>
                </li>
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Curabitur pharetra et diam in egestas</span>
                </li>
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path
                            d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
                    </svg>
                    <span class="leading-tight">Phasellus eu ligula metus</span>
                </li>
            </ul>
        </div>
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-900" id="statistics" role="tabpanel"
            aria-labelledby="statistics-tab">
            <dl
                class="grid max-w-screen-xl grid-cols-2 gap-8 p-4 mx-auto text-gray-900 sm:grid-cols-3 xl:grid-cols-6 dark:text-white sm:p-8">
                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">R$ 4.364,00</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Total a pagar</dd>
                </div>
                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">R$ 729,50</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Total Solicitado</dd>
                </div>
                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">R$ ***</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Saldo disponível</dd>
                </div>
            </dl>
        </div>
    </div>
</div>




{% endblock content %}

templates/dashboard/solicitacoes.html
{% extends "dashboard/_base.html" %}

{% block content %}


<div
    class="mx-auto w-full max-w-md p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-900 dark:border-gray-700">
    <div class="flex items-center justify-between mb-4">
        <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white">Últimas Solicitações</h5>
        <a href="{% url 'entregadores' %}" class="text-sm font-medium text-blue-600 hover:underline dark:text-blue-500">
            Ir para pagamentos
        </a>
    </div>
    <div class="flow-root">
        <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
            <li class="py-3 sm:py-4">
                <div class="flex items-center">

                    <div class="flex-1 min-w-0 ms-4">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Neil Sims
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Enviou uma solicitação de saque
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $320
                    </div>
                </div>
            </li>
            <li class="py-3 sm:py-4">
                <div class="flex items-center ">

                    <div class="flex-1 min-w-0 ms-4">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Bonnie Green
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Enviou uma solicitação de saque
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $3467
                    </div>
                </div>
            </li>
            <li class="py-3 sm:py-4">
                <div class="flex items-center">

                    <div class="flex-1 min-w-0 ms-4">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Michael Gough
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Enviou uma solicitação de saque
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $67
                    </div>
                </div>
            </li>
            <li class="py-3 sm:py-4">
                <div class="flex items-center ">

                    <div class="flex-1 min-w-0 ms-4">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Lana Byrd
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Enviou uma solicitação de saque
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $367
                    </div>
                </div>
            </li>
            <li class="pt-3 pb-0 sm:pt-4">
                <div class="flex items-center ">

                    <div class="flex-1 min-w-0 ms-4">
                        <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
                            Thomes Lean
                        </p>
                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                            Enviou uma solicitação de saque
                        </p>
                    </div>
                    <div class="inline-flex items-center text-base font-semibold text-gray-900 dark:text-white">
                        $2367
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>


{% endblock content %}